name: bitmask
description:  Package for Bitmask objects that can be created, modified, combined with bitmask operations.
version: 1.0.1
repository: https://github.com/jimorc/bitmask.git
issue_tracker: https://github.com/jimorc/bitmask/issues
documentation: https://jimorc.github.io/bitmask

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
