name: bitmask
description: A library containing a Bitmask class.
version: 1.0.0
repository: https://github.com/jimorc/bitmask.git
issue_tracker: https://github.com/jimorc/bitmask/issues

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
